development:
  adapter: mysql2
  encoding: utf8
  database: domsys
  username: root
  password:

daemons:
  adapter: mysql2
  encoding: utf8
  database: domsys
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: domsys
  username: root
  password:
